apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
  namespace: default
spec:  # Note: ConfigMaps don't actually use 'spec', they use 'data' directly
  data:
    index.html: |
      <!DOCTYPE html>
      <html>
      <body>
          <h1 style="color: blue;">GitOps Success!</h1>
          <p>The ConfigMap is now correctly populated.</p>
      </body>
      </html>