apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
spec:
  data:
    index.html: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>My GitOps Lab</title>
          <style>
              body { font-family: sans-serif; text-align: center; margin-top: 50px; background-color: #f4f4f4; }
              .card { border: 2px solid #00d1b2; padding: 20px; display: inline-block; background: white; border-radius: 10px; }
          </style>
      </head>
      <body>
          <div class="card">
              <h1>Hello from Argo CD! ðŸš€</h1>
              <p>Deployment managed via GitOps.</p>
              <p>Current Status: <b>Syncing with GitHub</b></p>
          </div>
      </body>
      </html>